# Name of our workflow which will act as an identifier when have multilple workflows.
name: Firebase Hosting Continuous Deployment

# Define trigger point, on push on master branch, this workflow will be triggered.
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm ci
      - run: npm run build
      - name: GitHub Action for Firebase
        uses: w9jds/firebase-action@v1.5.0
        with:
          args: deploy --only hosting
        env:


          FIREBASE_TOKEN: ${{ secrets.firebase_key }}
          # This is where our stored secret will come in use
